### ISSUE TITLE
관리자 페이지 설계 및 구현 논의

### ISSUE THREAD

**Issue by grayashh** [ConvergenceSwAce/MJS-admin-web#3]
- 각 식당별로 중식, 석식 메뉴를 입력할 수 있도록 폼을 제작 후에 저장하면 디비로 전송
- 식당 운영에 차질이 생기거나 공지사항이 있을 경우 학생들에게 공지사항이나 전달사항을 보여줄 수 있게 따로 폼 제작 (식당도 모든 학생들과의 컨택이 어려움)
  - 프론트에서도 메뉴 컴포넌트에 그냥 바로 보여줄건지 
  - Week Carousel 쪽에 전광판 처럼 지나가게 하던지 or 클릭하여 모달을 띄울건지
  - 해당 식단 시간표를 조회했을 때 아예 팝업을 띄워버릴건지
  - 위 사항들이 고려되야 함.

**Comment by MinsuKim21** [comment]
노션 ㄱ
